version: '3.7'

services:

  example:
    container_name: angular-blog
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules'
    ports:
      - '4201:4200'
